### ISSUE TITLE
Rename to OXRS-AC-I2CSensors-ESP-LIB

### ISSUE THREAD

**Issue by sumnerboy12** [austinscreations/OXRS-AC-I2CSensors-ESP-LIB#1]
You have one too many `-` delimiters in your name - will make it incompatible with any code to parse firmware names. 

Perhaps I2CSensors is a better name?

**Comment by austinscreations** [comment]
oh, i understand the structure now. totally glossed over the use of IO in the other libs
this has now been fixed
