### ISSUE TITLE
Consider changing to take a callback in constructor for retrieving IP/MAC addresses

### ISSUE THREAD

**Issue by sumnerboy12** [austinscreations/OXRS-AC-I2CSensors-ESP-LIB#6]
Instead of having all those different constructors for different hardware types, what about a simple callback which is called when required to update the OLED.

The firmware code can optionally implement and just return the IP and MAC address depending on how it is configured.

Something similar to how the API library handles generating the adoption payload.

**Comment by austinscreations** [comment]
I'm failing to see how do this in a nice way the OLED is what uses the mac and IP address - the oled is first called before you start your connection - showing you your mac address, then is called after you start your connection to then show you your IP address - so you can easily access the API and the mac being shown so you easily know your device ID

then you keep calling the oled in the loop to ensure it remains updated

as for passing it I'm failing to see a nice way to do it. (but i can learn)

**Comment by sumnerboy12** [comment]
What about `oled.begin(mac)` and `oled.loop(ipaddress)`?

Then the calling code can decide where to retrieve each bit of data from, and your library API is much simpler.

**Comment by austinscreations** [comment]
fixed with library 0.4.0
