### ISSUE TITLE
Prefix all serial debugging with `[sens] ` - i.e. 4 char unique code to help identify source

### ISSUE THREAD

**Issue by sumnerboy12** [austinscreations/OXRS-AC-I2CSensors-ESP-LIB#7]
And try to reduce serial logging to error conditions only - libraries shouldn't typically output debugging to serial - use return codes/constants if you need to report state back to the firmware, where it can decide how to log it.

**Comment by austinscreations** [comment]
completed in library v0.2.0 update - hopefully it's satisfactory
